### ISSUE TITLE
Mod Crashing Due To Starlight River being enabled

### ISSUE THREAD

**Issue by ELGashong** [BlockCrusader/BSWLmod#2]
After the update, the Weapon Enchantment mod crashes when another mod, Starlight River, is enabled. The crash happens when Tmodloader tries to add the recipes from the different mods. Here is what the crash log for it.

System.NullReferenceException: Object reference not set to an instance of an object.
   at WeaponEnchantments.Common.InfusionManager.GetWeaponInfusionPower(Item item, Boolean includeNonFinalizedInfusion) in WeaponEnchantments\Common\Infusion\InfusionManager.cs:line 348
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.ComputeMap(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at System.Linq.Enumerable.SelectIPartitionIterator`2.GetCount(Boolean onlyIfCheap)
   at androLib.Common.Utility.StringManipulation.JoinList(IEnumerable`1 list, String joinString, String last) in androLib\Common\Utility\StringManipulation.cs:line 551
   at androLib.Common.Utility.StringManipulation.S(IEnumerable`1 strings, String nameAndType, Int32 tabs, Boolean isArgument) in androLib\Common\Utility\StringManipulation.cs:line 121
   at WeaponEnchantments.Common.InfusionProgression.PopulateItemInfusionPowers() in WeaponEnchantments\Common\Infusion\InfusionProgression.cs:line 3789
   at WeaponEnchantments.Common.InfusionProgression.SetupDictionaries() in WeaponEnchantments\Common\Infusion\InfusionProgression.cs:line 1126
   at WeaponEnchantments.Common.InfusionProgression.PostSetupContent() in WeaponEnchantments\Common\Infusion\InfusionProgression.cs:line 1104
   at WeaponEnchantments.WEModSystem.PostAddRecipes() in WeaponEnchantments\WEModSystem.cs:line 65
   at Terraria.ModLoader.SystemLoader.PostAddRecipes(Mod mod) in tModLoader\Terraria\ModLoader\SystemLoader.cs:line 90
   at Terraria.ModLoader.RecipeLoader.PostAddRecipes() in tModLoader\Terraria\ModLoader\RecipeLoader.cs:line 67
   at Terraria.Recipe.SetupRecipes() in tModLoader\Terraria\Recipe.cs:line 14632
   at Terraria.ModLoader.ModContent.SetupRecipes(CancellationToken token) in tModLoader\Terraria\ModLoader\ModContent.cs:line 416
   at Terraria.ModLoader.ModContent.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModContent.cs:line 341
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 126

**Comment by BlockCrusader** [comment]
Uhh? This is BSWLmod - 'Block's Leveling Mod'. Not WeaponEnchantments. You're posting on the wrong mod's GitHub repository.
